{"uuid": "4e8b230f-f66d-4bbf-b4e1-bb5bf5fcd0be", "children": ["71912237-6f95-4872-82f7-bdb0e77f96e0"], "befores": [{"name": "app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 0\n\n", "trace": "  File \"c:\\users\\tnurt\\pycharmprojects\\python_traning\\env\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\tnurt\\pycharmprojects\\python_traning\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\tnurt\\pycharmprojects\\python_traning\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\tnurt\\PycharmProjects\\python_traning\\conftest.py\", line 27, in app\n    fixture = Application(browser=browser, base_url=web_config['baseUrl'])\n  File \"C:\\Users\\tnurt\\PycharmProjects\\python_traning\\fixture\\application.py\", line 10, in __init__\n    self.wd = webdriver.Firefox()\n  File \"c:\\users\\tnurt\\pycharmprojects\\python_traning\\env\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 170, in __init__\n    RemoteWebDriver.__init__(\n  File \"c:\\users\\tnurt\\pycharmprojects\\python_traning\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\users\\tnurt\\pycharmprojects\\python_traning\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"c:\\users\\tnurt\\pycharmprojects\\python_traning\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\tnurt\\pycharmprojects\\python_traning\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1621190652602, "stop": 1621190657856}], "start": 1621190652602, "stop": 1621190657966}